### PR TITLE
Add related single-purposed tools section

### PR DESCRIPTION
**Pull request by adriens**
cf #67

### CODE REVIEW

**Review by tamere-allo-peter — CHANGES_REQUESTED** [review]
@adriens please add a description for vimdiff

**Comment by adriens** [comment]
image

**Comment by adriens** [comment]
done 
image

**Review by tamere-allo-peter — APPROVED** [review]

**Comment by adriens** [comment]
Ready to be merged @tamere-allo-peter

**Comment by adriens** [comment]
:+1:

**Pull request merged**
