### PR TITLE
Add blog DEV.to post

### PR DESCRIPTION
**Pull request by adriens**
cf #48

### CODE REVIEW

**Comment by adriens** [comment]
Enjoy @tamere-allo-peter :gift:

**Review by tamere-allo-peter — CHANGES_REQUESTED** [review]
Please check what you wrote and fix. It's probably "DEV to" instead of "DE to".

**Comment by adriens** [comment]
:+1: 
Typo fixed commited

**Review by tamere-allo-peter — APPROVED** [review]

**Comment by adriens** [comment]
:zap:

**Pull request merged**
