### PR TITLE
Fix windows install step

### PR DESCRIPTION
**Pull request by adriens**
cf #41 @tamere-allo-peter

### CODE REVIEW

**Review by tamere-allo-peter — CHANGES_REQUESTED** [review]
No this is not good. The install should be the same on both systems, but it depends on which, and how many, Python interpreters are available on your system. For example if python3 is the only one on your system, chances are that there's a symlink from python to python3. 

IMHO you should not create an additional section for this, maybe add some comment like _NB : the name of your python executable might be different, YMMV._

**Comment by adriens** [comment]
Totally agree with you @tamere-allo-peter 

💩 https://stackoverflow.com/questions/40914108/bash-python3-command-not-found-windows-discord-py

**Comment by adriens** [comment]
Same worry on Powershell install : 
image

**Comment by tamere-allo-peter** [comment]
ok ok ok.

**Pull request merged**
